GET http://localhost:3001

##add new task
POST http://localhost:3001/new HTTP/1.1
Content-Type: application/json
{
    "description": "Test from REST Client"
}

//The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:3001.
